# Generated by Django 5.1.3 on 2024-11-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_transaction_deleted_alter_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Transaction_type',
            field=models.CharField(choices=[('CREDIT', 'CREDIT'), ('DEBIT', 'DEBIT')], max_length=10),
        ),
    ]
